### ISSUE TITLE
Setup initial Marketplace Deployment for GKE

### ISSUE THREAD

**Issue by etiennedi** [semi-technologies/weaviate-on-gcp-marketplace#1]
## Todos
* [x] setup public git repo
* [x] Build simple pipeline to
    * [x] make sure all [image/container requirements](https://cloud.google.com/marketplace/docs/partners/kubernetes-solutions/create-app-package?hl=en_US&_ga=2.266996877.-2009233886.1524043107&_gac=1.241371446.1578911513.EAIaIQobChMI1rCX2a2A5wIVQbDtCh1NBAqnEAAYASAAEgJofPD_BwE#application-images) are respected
    * [x] find out which images are used in our subcharts
    * [x] verify all charts allow overwrites of images, if not 
       * ~~adopt on own charts~~
       * ~~open PRs on foreign charts~~
    * [x] tag all images according to appVersion
    * [x] push into GCP repo
    * [x] run on travis on tag
       * [x] add gcp repo secrets from marketplace account
* [x] integrate billing container
  * ~~fork existing helm chart or add support for arbitrary side-cars~~
  * ~~include billing side car (*blocked by Google verifying our princing model*)~~
  * outscoped to #3 
* [x] build deployer image
  * [x] define `schema.yaml` in accordance with Helm chart, [see](https://github.com/GoogleCloudPlatform/marketplace-k8s-app-tools/blob/master/docs/schema.md)
    * come up with minimal configuration, e.g. no auto updates, no istio-support, etc. 
  * [x] add Helm process, see [Helm specific instructions](https://github.com/GoogleCloudPlatform/marketplace-k8s-app-tools/blob/master/docs/building-deployer-helm.md)
    * in first version, don't include `etcd` disaster recovery. This will result in an unstable setup, but it will be a bit easier to build, since we don't yet need a custom service account
    * [ ] include storage provisioner (requires [service acccount modifications](https://github.com/GoogleCloudPlatform/marketplace-k8s-app-tools/blob/master/docs/building-deployer-helm.md#declare-rbac-requirements-and-disable-rbac-in-the-chart))
  * [x] deal with [user-ability to set arguments](https://cloud.google.com/marketplace/docs/partners/kubernetes-solutions/create-app-package?hl=en_US&_ga=2.266996877.-2009233886.1524043107&_gac=1.241371446.1578911513.EAIaIQobChMI1rCX2a2A5wIVQbDtCh1NBAqnEAAYASAAEgJofPD_BwE#custom-parameters)
* [x] add required verification tests [as outlined here](https://github.com/GoogleCloudPlatform/marketplace-k8s-app-tools/blob/master/docs/verification-integration.md) and [here](https://cloud.google.com/marketplace/docs/partners/kubernetes-solutions/create-app-package?hl=en_US&_ga=2.266996877.-2009233886.1524043107&_gac=1.241371446.1578911513.EAIaIQobChMI1rCX2a2A5wIVQbDtCh1NBAqnEAAYASAAEgJofPD_BwE#verification-process)
  * [x] build tester pod
  * [x] build test pipeline ("verification intregration")
    * in theory this is completed, but doesn't work due to blocker #2
* [x] add K8s custom resource required for deployment
  * [x] find out about required structure
  * [x] create in repo
  * [x] define process for one-time-update (resource installation) vs subsequent updates (resource content updates)
* [x] include license in `LICENSE` file
* [ ] write user [guide according to this](https://cloud.google.com/marketplace/docs/partners/kubernetes-solutions/create-app-package?hl=en_US&_ga=2.266996877.-2009233886.1524043107&_gac=1.241371446.1578911513.EAIaIQobChMI1rCX2a2A5wIVQbDtCh1NBAqnEAAYASAAEgJofPD_BwE#user-guide)
